name: 'functionnal test python'

on:
  push:
    branches:
      - "cd_ci"

jobs:
  functionnalTests:
    name: 'Does it run?'
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: cd_ci
      - name: install requirements
        run: cd src; pip3 install -r requirements.txt
      - name: launch transpiler
        run: cd src; python3 main.py ./react ./tests/src > result.txt  2>> result.txt
      - name: load failure artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: pythonErrorReport.txt
          path: ./src/result.txt
      - name: load succes artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: pythonSuccessReport.txt
          path: ./src/result.txt
