name: 'functional tests'

on:
  push:
    branches:
      - "cd_ci"

jobs:
  functionalTests:
    name: 'functional tests'
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: cd_ci
      - name: install requirements
        run: cd src; pip3 install -r requirements.txt
      - name: launch transpiler
        run: cd src; python3 main.py ./react ./tests/src > result.txt 2> errors.txt
      - name: load failure artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: pythonErrorReport.txt
          path: ./src/errors.txt
